# Generated by Django 5.1.7 on 2025-04-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_file', models.FileField(upload_to='student_file/')),
                ('file_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
